name: Test specified tags

on:
  repository_dispath:
    types:
      - 'test-wheel'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        pkg: ['scm', 'scm-dep', 'scm-base']

    steps:
    - name: Checkout ${{ matrix.pkg }}
      uses: actions/checkout@v3
      with:
        repository: 'suvayu/${{ matrix.pkg }}'
        ref: github.event.client_payload.${{ matrix.pkg }}.tag
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build
      run: |
        python -m build -o dist/ ${{ matrix.pkg }}

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Install pytest and built wheels
      run: |
        pip install pytest
        pip install dist/*.whl
    - name: Test scm
      run: |
        python -m pytest scm/tests/
