name: Test specified tags

on:
  workflow_dispatch:
    inputs:
      scm:
        description: Git tag to use for 'scm'
        required: true
        type: string
      scm-dep:
        description: Git tag to use for 'scm-dep'
        required: true
        type: string
      scm-base:
        description: Git tag to use for 'scm-base'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        pkg: ['scm', 'scm-dep', 'scm-base']

    steps:
    - name: Checkout ${{ matrix.pkg }}
      uses: actions/checkout@v3
      with:
        repository: 'suvayu/${{ matrix.pkg }}'
        ref: inputs.${{ matrix.pkg }}
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build
      run: |
        python -m build -o dist/ ${{ matrix.pkg }}

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Install pytest and built wheels
      run: |
        pip install pytest
        pip install dist/*.whl
    - name: Test scm
      run: |
        python -m pytest scm/tests/
