name: Test specified tags

on:
  workflow_dispatch:
    inputs:
      scm:
        description: Git tag to use for 'scm'
        required: true
        type: string
        default: 'skip'
      scm-dep:
        description: Git tag to use for 'scm-dep'
        required: true
        type: string
        default: 'skip'
      scm-base:
        description: Git tag to use for 'scm-base'
        required: true
        type: string
        default: 'skip'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        pkg: ['scm', 'scm-dep', 'scm-base']
        python: ["3.12"]

    steps:
    - name: Checkout ${{ matrix.pkg }}
      uses: actions/checkout@v4
      with:
        repository: 'suvayu/${{ matrix.pkg }}'
        path: ${{ matrix.pkg }}
        ref: ${{ inputs[matrix.pkg] }}
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install build
    - name: Build
      if: inputs[matrix.pkg] != 'skip'
      run: |
        python -m build ${{ matrix.pkg }}
    - name: Download wheels for packages excluded from build
      if: inputs[matrix.pkg] == 'skip'
      run: |
        mkdir -p ${{ matrix.pkg }}/dist/
        sed -nEe 's/name[ ]*=[ ]*"?([a-z0-9_-]+)"?/\1/p' ${{ matrix.pkg }}/pyproject.toml > pkgname
        python -m pip download -i https://test.pypi.org/simple \
          --no-deps --python-version ${{ matrix.python }} \
          --dest ${{ matrix.pkg }}/dist/ $(cat pkgname)
    - name: Save ${{ matrix.pkg }} wheel
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.pkg }}
        path: ${{ matrix.pkg }}/dist/*
        retention-days: 7

  test:
    needs: build
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python: ["3.8", "3.9", "3.10", "3.11", "3.12"]
      fail-fast: false

    uses: ./.github/workflows/test-wheel.yml
    with:
      ver: ${{ inputs.scm }}
      os: ${{ matrix.os }}
      python: ${{ matrix.python }}

  publish:
    # isolate from test, to prevent partial uploads
    needs: test
    strategy:
      matrix:
        pkg: ['scm', 'scm-dep', 'scm-base']

    uses: ./.github/workflows/publish-wheel.yml
    with:
      pkg: ${{ matrix.pkg }}
      ver: ${{ inputs[matrix.pkg] }}
